# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports = [ ];

  boot.initrd.availableKernelModules = [ "ata_piix" "mptspi" "floppy" "sd_mod" "sr_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];
  boot.initrd.luks.devices = {
    cryptroot.device = "/dev/disk/by-uuid/c0403131-bb45-4c0c-a5f7-abd013413b11";
    cryptswap.device = "/dev/disk/by-uuid/ab8bc225-0283-473e-8c83-c5efa27e8034";
  };

  fileSystems."/" =
    { device = "tank0/local/root";
      fsType = "zfs";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/03e81d34-63b0-4cfb-bd0b-8fdc413b18a2";
      fsType = "ext4";
    };

  fileSystems."/home" =
    { device = "tank0/safe/home";
      fsType = "zfs";
    };

  fileSystems."/persist" =
    { device = "tank0/safe/persist";
      fsType = "zfs";
    };

  swapDevices =
    [ { device = "/dev/mapper/cryptswap"; }
    ];

  nix.maxJobs = lib.mkDefault 8;
}
