# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ];

  boot.initrd.availableKernelModules = [ "nvme" "ehci_pci" "xhci_pci" "ahci" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  boot.initrd.luks.devices = {
    acryptkey.device = "/dev/disk/by-uuid/1c7c3ac4-a0b4-425b-ae3b-9918bf57af2f";

    cryptdev0 = {
      device = "/dev/disk/by-uuid/8f1fa970-ab84-4b0a-96c8-4e0d1cdc57e1";
      keyFile = "/dev/mapper/acryptkey";
    };
    cryptdev1 = {
      device = "/dev/disk/by-uuid/8876c012-a7a8-4d60-a85f-b915da20d05f";
      keyFile = "/dev/mapper/acryptkey";
    };
  };

  boot.initrd.postMountCommands = ''
    # Close LUKS key
    cryptsetup close /dev/mapper/acryptkey
  '';

  # Clean root at boot
  # Thanks to Graham Christensen: https://grahamc.com/blog/erase-your-darlings
  boot.initrd.postDeviceCommands = lib.mkAfter ''
    zfs rollback -r tank0/local/root@empty
  '';

  fileSystems."/" =
    { device = "tank0/local/root";
      fsType = "zfs";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/71BC-BC1C";
      fsType = "vfat";
    };

  fileSystems."/home" =
    { device = "tank0/safe/home";
      fsType = "zfs";
    };

  fileSystems."/nix" =
    { device = "tank0/local/nix";
      fsType = "zfs";
    };

  fileSystems."/persistent" =
    { device = "tank0/safe/persistent";
      fsType = "zfs";
    };

  fileSystems."/var/lib/libvirt" =
    { device = "tank0/safe/libvirt";
      fsType = "zfs";
    };

  fileSystems."/data" =
    { device = "tank1/data";
      fsType = "zfs";
    };

  swapDevices = [ ];

  nix.maxJobs = lib.mkDefault 32;
  # High-DPI console
  console.font = lib.mkDefault "${pkgs.terminus_font}/share/consolefonts/ter-u28n.psf.gz";
}
