# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ];

  boot.initrd.availableKernelModules = [ "ahci" "xhci_pci" "usbhid" "usb_storage" "sd_mod" "sdhci_pci" "battery" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  boot.initrd.luks.devices = {
    cryptroot.device = "/dev/disk/by-uuid/9938e11d-6175-438a-aaa5-855d2030278f";
    cryptswap.device = "/dev/disk/by-uuid/454ef386-ace8-4b7e-9a21-807717a76ca1";
  };

  fileSystems."/" =
    { device = "tank/local/root";
      fsType = "zfs";
    };

  fileSystems."/home" =
    { device = "tank/safe/home";
      fsType = "zfs";
    };

  fileSystems."/nix" =
    { device = "tank/local/nix";
      fsType = "zfs";
    };

  fileSystems."/persist" =
    { device = "tank/safe/persist";
      fsType = "zfs";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/5064-1E2E";
      fsType = "vfat";
    };

  swapDevices =
    [ { device = "/dev/mapper/cryptswap"; }
    ];

  nix.maxJobs = lib.mkDefault 4;
  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
}
