# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/profiles/qemu-guest.nix")
    ];

  boot.initrd.availableKernelModules = [ "ata_piix" "uhci_hcd" "virtio_pci" "sr_mod" "virtio_blk" "virtio_net" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  boot.initrd.luks.devices = {
    cryptdev0.device = "/dev/disk/by-uuid/6b3633f1-e176-4cdc-a59c-df47dbb7f564";
    cryptswap.device = "/dev/disk/by-uuid/79744261-2ece-4015-9e74-d76dc80c8787";
  };

  fileSystems."/" =
    { device = "tank0/local/root";
      fsType = "zfs";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/3eaac461-45e4-48aa-8cbd-ead7e9253a66";
      fsType = "ext4";
    };

  fileSystems."/nix" =
    { device = "tank0/local/nix";
      fsType = "zfs";
    };

  fileSystems."/home" =
    { device = "tank0/safe/home";
      fsType = "zfs";
    };

  fileSystems."/persist" =
    { device = "tank0/safe/persist";
      fsType = "zfs";
    };

  swapDevices = [ { device = "/dev/mapper/cryptswap"; size = 2031; } ];

}
