# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "nvme" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  boot.initrd.luks.devices = {
    cryptdisk0.device = "/dev/disk/by-uuid/5481752b-cd6d-480e-aa7a-a1f38a8dc41a";
    cryptswap.device = "/dev/disk/by-uuid/f0190f9e-1ed1-4b9d-8546-462606614412";
  };

  fileSystems."/" =
    { device = "tank0/local/root";
      fsType = "zfs";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/C677-7660";
      fsType = "vfat";
    };

  fileSystems."/nix" =
    { device = "tank0/local/nix";
      fsType = "zfs";
    };

  fileSystems."/home" =
    { device = "tank0/safe/home";
      fsType = "zfs";
    };

  fileSystems."/persist" =
    { device = "tank0/safe/persist";
      fsType = "zfs";
    };

  swapDevices = [
      { device = "/dev/mapper/cryptswap"; }
    ];

  powerManagement = {
    #cpuFreqGovernor = lib.mkDefault "powersave";
    powertop.enable = true;
  };
  # high-resolution display
  hardware.video.hidpi.enable = lib.mkDefault true;
}
